name: course_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.30.1
  package_info_plus: ^7.0.0
  equatable: ^2.0.5
  dartz: ^0.10.1
  flutter_bloc: ^8.1.5
  bloc: ^8.1.4
  get_it: ^7.6.9
  file_picker: ^8.0.2
  font_awesome_flutter: ^10.7.0
  iconly: ^1.0.1
  image_picker: ^1.1.0
  intl: ^0.18.1
  open_file: ^3.3.2
  path_provider: ^2.1.3
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  smooth_page_indicator: ^1.1.0
  swipe_to: ^1.0.6
  url_launcher: ^6.2.6
  youtube_metadata: ^1.0.1
  video_thumbnail: ^0.5.3
  chewie: ^1.8.1
  http: ^0.13.6
  lottie: ^3.0.0
  cupertino_icons: ^1.0.8
  firebase_auth: ^4.19.4
  cloud_firestore: ^4.17.2
  firebase_storage: ^11.7.4
  firebase_ui_auth: ^1.7.0
  uuid: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mocktail: ^1.0.3
  bloc_test: ^9.1.7
  very_good_analysis: ^5.1.0
  firebase_auth_mocks: ^0.13.0
  google_sign_in_mocks: ^0.3.0
  fake_cloud_firestore: ^2.5.1
  firebase_storage_mocks: ^0.6.1

flutter:
  uses-material-design: true


  assets:
    - assets/vectors/
    - assets/images/
    - assets/lottie/
    - assets/icons/


  fonts:
      - family: Aeonik
        fonts:
          - asset: assets/fonts/aeonik/AeonikTRIAL-Bold.otf
            weight: 700
          - asset: assets/fonts/aeonik/AeonikTRIAL-BoldItalic.otf
            weight: 700
          - asset: assets/fonts/aeonik/AeonikTRIAL-Light.otf
            weight: 300
          - asset: assets/fonts/aeonik/AeonikTRIAL-LightItalic.otf
            style: italic
            weight: 300
          - asset: assets/fonts/aeonik/AeonikTRIAL-Regular.otf
            weight: 400
          - asset: assets/fonts/aeonik/AeonikTRIAL-RegularItalic.otf
            style: italic
            weight: 400
      - family: Poppins
        fonts:
          - asset: assets/fonts/poppins/Poppins-Thin.ttf
            weight: 100
          - asset: assets/fonts/poppins/Poppins-ExtraLight.ttf
            weight: 200
          - asset: assets/fonts/poppins/Poppins-Light.ttf
            weight: 100
          - asset: assets/fonts/poppins/Poppins-Regular.ttf
            weight: 100
          - asset: assets/fonts/poppins/Poppins-Medium.ttf
            weight: 100
          - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
            weight: 100
          - asset: assets/fonts/poppins/Poppins-Bold.ttf
            weight: 100
          - asset: assets/fonts/poppins/Poppins-ExtraBold.ttf
            weight: 100
