// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNweZY05_wiQw75wVR-KlP3RyXC3Nvd3k',
    appId: '1:625244293243:android:c312a93b65a6097826bade',
    messagingSenderId: '625244293243',
    projectId: 'course-app-be0f3',
    storageBucket: 'course-app-be0f3.appspot.com',
  );

  // static const FirebaseOptions ios = FirebaseOptions(
  //   apiKey: 'AIzaSyA1JAIeBH9-75zUnCNFER64aChR7PdNNtM',
  //   appId: '1:625244293243:ios:82c55fcfde29bf4226bade',
  //   messagingSenderId: '625244293243',
  //   projectId: 'course-app-be0f3',
  //   storageBucket: 'course-app-be0f3.appspot.com',
  //   iosBundleId: 'com.dbestech.courseApp',
  // );

  // static const FirebaseOptions web = FirebaseOptions(
  //   apiKey: 'YOUR_WEB_API_KEY',
  //   authDomain: 'YOUR_AUTH_DOMAIN',
  //   projectId: 'YOUR_PROJECT_ID',
  //   storageBucket: 'YOUR_STORAGE_BUCKET',
  //   messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
  //   appId: 'YOUR_APP_ID',
  //   measurementId: 'YOUR_MEASUREMENT_ID',
  // );

}
